markdown: kramdown
highlighter: rouge

kramdown:
  auto_ids: true

permalink: pretty
source: docs
baseurl: ""

version: 2.2.1

sass:
  sass_dir: ../
  style: compressed

github:
  repo: https://ghosthub.corp.blizzard.net/web-and-mobile/skeleton-less
